AWSTemplateFormatVersion: '2010-09-09'
Description: "Stack for Amazon Redshift cookbook chapter2"
Parameters:
  CookbookIAMUserName:
    Type: String
    Description: Session name must satisfy regular expression pattern ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
    Default: ""
  CookbookBucketName:
    Type: String
    Description: Session name must satisfy regular expression pattern ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
    Default: ""
  RedshiftClusterRole:
    Type: String
    Description: redshift cluster role name
    Default: ""         
Resources:
  Chapter2IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Chapter2IAMPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:*
          Resource:
          - '*'
        - Effect: Allow
          Action:
          - redshift:*
          - redshift-data:*   
          - kms:*          
          Resource:
          - '*'
      Users:
          - !Ref CookbookIAMUserName

  Chapter2LambdaInvokePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${CookbookBucketName}"
              - !Sub "arn:aws:s3:::${CookbookBucketName}/*"
      Roles: 
          - !Ref RedshiftClusterRole   

Outputs:
  Chapter2IAMPolicy:
    Description: "IAM policy access to create lamdbda function"
    Value: !Ref Chapter2IAMPolicy
  Chapter2LambdaInvokePolicy:
    Description: "Attached this policy to Redshift cluster role for lambda invoke and s3 access"
    Value: !Ref Chapter2LambdaInvokePolicy
