AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Amazon Redshift cookbook Chapter8
Parameters:
  CookbookIAMUserName:
    Type: String
    Description: cookbook iam user name
    Default: ''
  CookbookBucketName:
    Type: String
    Description: >-
      Session name must satisfy regular expression pattern
      ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
    Default: ''
  RedshiftClusterRole:
    Type: String
    Description: redshift cluster role name
    Default: ''
Resources:
  Chapter8RedshiftSchedulerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: IAM Role for Redshift scheduler
      RoleName: Chapter8RedshiftSchedulerRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: 
                - scheduler.redshift.amazonaws.com
                - redshift.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
            
  Chapter8IAMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: Chapter8IAMPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'redshift:*'
              - 'redshift-data:*'
              - 'secretsmanager:*'
              - 'logs:*'
              - 'sns:*'
              - 'cloudwatch:*'
              - 'cloudformation:*'
              - 'kms:*'
              - 'glue:*'
              - 'ec2:*'
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation  
              - trustedadvisor:Describe* 
              - aws-portal:ViewAccount
              - aws-portal:ViewBilling              
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${CookbookBucketName}"
              - !Sub "arn:aws:s3:::${CookbookBucketName}/*"               
      Users:
        - !Ref CookbookIAMUserName
  Chapter8RedshiftPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${CookbookBucketName}'
              - !Sub 'arn:aws:s3:::${CookbookBucketName}/*'
          - Effect: Allow
            Action:
              - glue:*  
            Resource:
              - '*'              
      Roles:
        - !Ref RedshiftClusterRole
Outputs:
  Chapter8IAMPolicy:
    Description: IAM policy access for chapter 8
    Value: !Ref Chapter8IAMPolicy
  Chapter8RedshiftPolicy:
    Description: Chapter8 redshift policy
    Value: !Ref Chapter8RedshiftPolicy
  Chapter8RedshiftSchedulerRole:
    Description: Chapter8 redshift scheduler role for elastic resize, pause and resume
    Value: !GetAtt Chapter8RedshiftSchedulerRole.Arn
           
