set enable_result_cache_for_session to off;
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --& 
SELECT         SUM(l_quantity) AS quantity,        SUM(l_extendedprice) AS extendedprice FROM lineitem WHERE   L_RECEIPTDATE         = '1992-01-29';     --&
SELECT o_orderstatus,        COUNT(o_orderkey) AS orders_count,        SUM(l_quantity) AS quantity,        MAX(l_extendedprice) AS extendedprice FROM lineitem   JOIN orders ON l_orderkey = o_orderkey WHERE   L_SHIPDATE = '1992-01-29' GROUP BY o_orderstatus;  --&

