AWSTemplateFormatVersion: '2010-09-09'
Description: "Stack for Amazon Redshift cookbook chapter3"
Parameters:
  CookbookIAMUserName:
    Type: String
    Description: cookbook iam user name
    Default: ""  
  CookbookBucketName:
    Type: String
    Description: Session name must satisfy regular expression pattern ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
    Default: ""    
  RedshiftClusterRole:
    Type: String
    Description: redshift cluster role name
    Default: ""   
Resources:
  Chapter3IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Chapter3IAMPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - emr:*
          - redshift:*
          - redshift-data:*    
          - kms:*
          - dynamodb:*
          - ec2:*     
          - secretmanager:*  
          - cfn:*          
          Resource:
          - '*'
      Users: 
          - !Ref CookbookIAMUserName

  Chapter3RedshiftPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:      
        - Effect: Allow
          Action:
          - dynamodb:scan
          - dynamodb:Describe*
          Resource: 
          - '*'
        - Effect: Allow
          Action:
          - s3:*
          Resource:
          - !Sub "arn:aws:s3:::${CookbookBucketName}"
          - !Sub "arn:aws:s3:::${CookbookBucketName}/*"     
        - Effect: Allow
          Action:
          - glue:CreateDatabase
          - glue:DeleteDatabase
          - glue:GetDatabase 
          - glue:GetDatabases 
          - glue:UpdateDatabase 
          - glue:CreateTable 
          - glue:DeleteTable 
          - glue:BatchDeleteTable 
          - glue:UpdateTable 
          - glue:GetTable 
          - glue:GetTables 
          - glue:BatchCreatePartition 
          - glue:CreatePartition 
          - glue:DeletePartition 
          - glue:BatchDeletePartition 
          - glue:UpdatePartition 
          - glue:GetPartition 
          - glue:GetPartitions 
          - glue:BatchGetPartition  
          Resource: 
          - '*'              
      Roles: 
          - !Ref RedshiftClusterRole               
            
Outputs:
  Chapter3IAMPolicy:
    Description: "IAM policy access to create EMR"
    Value: !Ref Chapter3IAMPolicy
  Chapter3RedshiftPolicy:
    Description: "managed policy for dynamodb, s3 and glueconsole access for Amazon Redshift"
    Value: !Ref Chapter3RedshiftPolicy  
